### ISSUE TITLE
????

### ISSUE THREAD

**Issue by soyouzpanda** [hugosimony/LG-UHC#1]
https://github.com/hugosimony/LG-UHC/blob/83325a3209b88416929bb123c52f9420bb2c9c09/src/fr/hugosimony/lguhc/Main.java#L126-L138

Pourquoi instancier à chaque commande une nouvelle fois Roles, alors qu'on peut l'instancier qu'une seule fois et passer cette instance pour toutes les commandes ?

**Comment by hugosimony** [comment]
C'est vrai, ça aurait été plus propre de mettre l'instance dans une variable.
C'est un vieux plugin, je découvrais encore un peu le spigot (et le java aussi en vrai) :p
Je vais fix ça en tout cas.
